

# This file was *autogenerated* from the file graphs.sage
from sage.all_cmdline import *   # import sage library

_sage_const_0 = Integer(0); _sage_const_1 = Integer(1); _sage_const_2 = Integer(2); _sage_const_4 = Integer(4); _sage_const_5 = Integer(5); _sage_const_3 = Integer(3); _sage_const_6 = Integer(6); _sage_const_12 = Integer(12); _sage_const_9 = Integer(9); _sage_const_10 = Integer(10); _sage_const_8 = Integer(8); _sage_const_7 = Integer(7); _sage_const_11 = Integer(11); _sage_const_14 = Integer(14); _sage_const_13 = Integer(13); _sage_const_16 = Integer(16); _sage_const_15 = Integer(15)
from moy import *
i = var('i')
j = var('j')

planar_handcuff = MOY([V([(_sage_const_0 ,i)],[(_sage_const_1 ,_sage_const_0 ),(_sage_const_0 ,i)]),V([(_sage_const_2 ,j), (_sage_const_1 ,_sage_const_0 )], [(_sage_const_2 ,j)])])

hopf_handcuff = MOY([X([(_sage_const_4 ,j),(_sage_const_1 ,i),(_sage_const_5 ,j),(_sage_const_2 ,i)]),X([(_sage_const_2 ,i),(_sage_const_5 ,j),(_sage_const_3 ,i),(_sage_const_6 ,j)]),V([(_sage_const_6 ,j)],[(_sage_const_0 ,_sage_const_0 ),(_sage_const_4 ,j)]), V([(_sage_const_0 ,_sage_const_0 ),(_sage_const_3 ,i)],[(_sage_const_1 ,i)])])

planar_theta = MOY([V([(_sage_const_2 ,i+j)], [(_sage_const_0 ,i), (_sage_const_1 ,j)]), V([(_sage_const_1 ,j), (_sage_const_0 ,i)],[(_sage_const_2 ,i+j)])])

X1 = X([(_sage_const_0 ,_sage_const_1 ),(_sage_const_4 ,_sage_const_1 ),(_sage_const_1 ,_sage_const_1 ),(_sage_const_3 ,_sage_const_1 )])
X2 = X([(_sage_const_4 ,_sage_const_1 ),(_sage_const_2 ,_sage_const_1 ),(_sage_const_5 ,_sage_const_1 ),(_sage_const_1 ,_sage_const_1 )])
V1 = V([(_sage_const_5 ,_sage_const_1 ),(_sage_const_2 ,_sage_const_1 )],[(_sage_const_0 ,_sage_const_1 ),(_sage_const_3 ,_sage_const_1 )])
singular_trefoil = MOY([X1,X2,V1])

V1 = V([(_sage_const_12 ,i+j)],[(_sage_const_5 ,i),(_sage_const_0 ,j)])
V2 = V([(_sage_const_9 ,i), (_sage_const_4 ,j)],[(_sage_const_10 ,i+j)])
X1 = X([(_sage_const_0 ,j),(_sage_const_9 ,i),(_sage_const_1 ,j),(_sage_const_8 ,i)])
X2 = X([(_sage_const_7 ,i),(_sage_const_12 ,i+j),(_sage_const_8 ,i),(_sage_const_11 ,i+j)])
X3 = X([(_sage_const_10 ,i+j),(_sage_const_2 ,j),(_sage_const_11 ,i+j),(_sage_const_1 ,j)])
X4 = X([(_sage_const_2 ,j),(_sage_const_6 ,i),(_sage_const_3 ,j),(_sage_const_7 ,i)])
X5 = X([(_sage_const_5 ,i),(_sage_const_3 ,j),(_sage_const_6 ,i),(_sage_const_4 ,j)])
theta_5_1 = MOY([V1,V2,X1,X2,X3,X4,X5])

V1 = V([(_sage_const_7 ,i),(_sage_const_3 ,j)],[(_sage_const_8 ,i+j)])
V2 = V([(_sage_const_14 ,i+j)],[(_sage_const_4 ,i),(_sage_const_0 ,j)])
X1 = X([(_sage_const_5 ,i), (_sage_const_2 ,j), (_sage_const_6 ,i), (_sage_const_1 ,j)])
X2 = X([(_sage_const_2 ,j), (_sage_const_13 ,i+j), (_sage_const_3 ,j), (_sage_const_12 ,i+j)])
X3 = X([(_sage_const_11 ,i+j), (_sage_const_6 ,i), (_sage_const_12 ,i+j), (_sage_const_7 ,i)])
X4 = X([(_sage_const_0 ,j), (_sage_const_10 ,i+j), (_sage_const_1 ,j), (_sage_const_11 ,i+j)])
X5 = X([(_sage_const_9 ,i+j), (_sage_const_5 ,i), (_sage_const_10 ,i+j), (_sage_const_4 ,i)])
X6 = X([(_sage_const_13 ,i+j), (_sage_const_9 ,i+j), (_sage_const_14 ,i+j), (_sage_const_8 ,i+j)])
theta_6_1 = MOY([V1,V2,X1,X2,X3,X4,X5,X6])

V1 = V([(_sage_const_16 ,i),(_sage_const_6 ,j)],[(_sage_const_7 ,i+j)])
V2 = V([(_sage_const_11 ,i+j)],[(_sage_const_12 ,i),(_sage_const_0 ,j)])
X1 = X([(_sage_const_9 ,i+j), (_sage_const_15 ,i), (_sage_const_10 ,i+j), (_sage_const_16 ,i)])
X2 = X([(_sage_const_5 ,j), (_sage_const_11 ,i+j), (_sage_const_6 ,j), (_sage_const_10 ,i+j)])
X3 = X([(_sage_const_14 ,i), (_sage_const_5 ,j), (_sage_const_15 ,i), (_sage_const_4 ,j)])
X4 = X([(_sage_const_3 ,j), (_sage_const_14 ,i), (_sage_const_4 ,j), (_sage_const_13 ,i)])
X5 = X([(_sage_const_12 ,i), (_sage_const_3 ,j), (_sage_const_13 ,i), (_sage_const_2 ,j)])
X6 = X([(_sage_const_1 ,j), (_sage_const_8 ,i+j), (_sage_const_2 ,j), (_sage_const_9 ,i+j)])
X7 = X([(_sage_const_7 ,i+j), (_sage_const_0 ,j), (_sage_const_8 ,i+j), (_sage_const_1 ,j)])
theta_7_1 = MOY([V1,V2,X1,X2,X3,X4,X5,X6,X7])

V1 = V([(_sage_const_6 ,i),(_sage_const_16 ,j)],[(_sage_const_7 ,i+j)])
V2 = V([(_sage_const_9 ,i+j)],[(_sage_const_0 ,i),(_sage_const_10 ,j)])
X1 = X([(_sage_const_11 ,j), (_sage_const_4 ,i), (_sage_const_12 ,j), (_sage_const_5 ,i)])
X2 = X([(_sage_const_5 ,i), (_sage_const_10 ,j), (_sage_const_6 ,i), (_sage_const_11 ,j)])
X3 = X([(_sage_const_8 ,i+j), (_sage_const_13 ,j), (_sage_const_9 ,i+j), (_sage_const_12 ,j)])
X4 = X([(_sage_const_3 ,i), (_sage_const_8 ,i+j), (_sage_const_4 ,i), (_sage_const_7 ,i+j)])
X5 = X([(_sage_const_13 ,j), (_sage_const_3 ,i), (_sage_const_14 ,j), (_sage_const_2 ,i)])
X6 = X([(_sage_const_1 ,i), (_sage_const_15 ,j), (_sage_const_2 ,i), (_sage_const_14 ,j)])
X7 = X([(_sage_const_15 ,j), (_sage_const_1 ,i), (_sage_const_16 ,j), (_sage_const_0 ,i)])
theta_7_2 = MOY([V1,V2,X1,X2,X3,X4,X5,X6,X7])

V1 = V([(_sage_const_7 ,j),(_sage_const_6 ,i)],[(_sage_const_8 ,i+j)])
V2 = V([(_sage_const_16 ,i+j)],[(_sage_const_4 ,j),(_sage_const_0 ,i)])
X1 = X([(_sage_const_0 ,i), (_sage_const_13 ,i+j), (_sage_const_1 ,i), (_sage_const_12 ,i+j)])
X2 = X([(_sage_const_13 ,i+j), (_sage_const_4 ,j), (_sage_const_14 ,i+j), (_sage_const_5 ,j)])
X3 = X([(_sage_const_5 ,j), (_sage_const_2 ,i), (_sage_const_6 ,j), (_sage_const_1 ,i)])
X4 = X([(_sage_const_11 ,i+j), (_sage_const_7 ,j), (_sage_const_12 ,i+j), (_sage_const_6 ,j)])
X5 = X([(_sage_const_2 ,i), (_sage_const_10 ,i+j), (_sage_const_3 ,i), (_sage_const_11 ,i+j)])
X6 = X([(_sage_const_9 ,i+j), (_sage_const_15 ,i+j), (_sage_const_10 ,i+j), (_sage_const_14 ,i+j)])
X7 = X([(_sage_const_15 ,i+j), (_sage_const_9 ,i+j), (_sage_const_16 ,i+j), (_sage_const_8 ,i+j)])
theta_7_3 = MOY([V1,V2,X1,X2,X3,X4,X5,X6,X7])

V1 = V([(_sage_const_7 ,j),(_sage_const_6 ,i)],[(_sage_const_8 ,i+j)])
V2 = V([(_sage_const_16 ,i+j)],[(_sage_const_4 ,j),(_sage_const_0 ,i)])
X1 = X([(_sage_const_0 ,i), (_sage_const_13 ,i+j), (_sage_const_1 ,i), (_sage_const_12 ,i+j)])
X2 = X([(_sage_const_13 ,i+j), (_sage_const_4 ,j), (_sage_const_14 ,i+j), (_sage_const_5 ,j)])
X3 = X([(_sage_const_5 ,j), (_sage_const_2 ,i), (_sage_const_6 ,j), (_sage_const_1 ,i)])
X4 = X([(_sage_const_11 ,i+j), (_sage_const_7 ,j), (_sage_const_12 ,i+j), (_sage_const_6 ,j)])
X5 = X([(_sage_const_2 ,i), (_sage_const_10 ,i+j), (_sage_const_3 ,i), (_sage_const_11 ,i+j)])
X6 = X([(_sage_const_14 ,i+j), (_sage_const_9 ,i+j), (_sage_const_15 ,i+j), (_sage_const_10 ,i+j)])
X7 = X([(_sage_const_8 ,i+j), (_sage_const_15 ,i+j), (_sage_const_9 ,i+j), (_sage_const_16 ,i+j)])
theta_7_4 = MOY([V1,V2,X1,X2,X3,X4,X5,X6,X7])

